# Generated by Django 2.2.3 on 2019-10-17 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20191017_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='post date:'),
            preserve_default=False,
        ),
    ]
