# Generated by Django 2.2.3 on 2020-01-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, height_field=500, null=True, upload_to='product/', width_field=500),
        ),
    ]
