# Generated by Django 2.2.3 on 2020-02-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_cart_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
