# Generated by Django 2.2.3 on 2020-02-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_orderproduct_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('A', 'Appliance'), ('C', 'Computer'), ('T', 'Toy')], max_length=1, null=True),
        ),
    ]
