# Generated by Django 2.2.3 on 2020-02-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('A', 'Appliance'), ('C', 'Computer'), ('T', 'Toy')], default='C', max_length=1),
        ),
    ]
