# Generated by Django 2.2.3 on 2020-02-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20200224_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('A', 'Appliance'), ('C', 'Computer'), ('T', 'Toy')], max_length=1),
        ),
    ]
